/* eslint-disable no-var */
export var config = {
  aliasPrefixes: { '~': 'node_modules/' },
  banner: '// Autogenerated file, do not modify',
  exportType: 'default',
  exportTypeInterface: 'IStyles',
  exportTypeName: 'ModuleClassNames',
  nameFormat: ['kebab'],
  updateStaleOnly: true
};
